### ISSUE TITLE
Correção formulário de aprovação de vinculação

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#114]
Formulário está permitindo colocar aprovada após colocar "Pendente"

Eliminar campo "Despacho da atual situação"

As informações de situação atual devem aparecer em seguida nas consultas das vinculações aprovadas e rejeitadas

**Comment by jessica-minc** [comment]
não foi para produção

**Comment by jessica-minc** [comment]
Depois que o processo de vinculação simplificado foi para produção, TODAS as vinculações deram erro. O gestor minc aprova o vínculo e recebe mensagem de que o vínculo foi recusado. Essa demanda é urgente!

**Comment by jessica-minc** [comment]
ok na produção
