### ISSUE TITLE
Completar as informações do detalhe do evento da praça

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#119]
1. Nem todas as informações aparecem quando o usuário não está logado, checar quais aparecem somente para o gestor minc ou gesto praça e torná-las disponíveis para qualquer usuário (mesmo sem login).

2. Nem todas as informações do evento estão aparecendo no detalhamento da praça, por exemplo Atividade, Área e Subárea não aparecem.

**Comment by jessica-minc** [comment]
não foi para produção

**Comment by jessica-minc** [comment]
não é possível preencher as informações de evento, ao adicionar atividade. Os seguintes campos estão com BUG (aparecencondo em branco): tipo de atividade; faixa etária; abrangência territorial; atividade destinada a Público ou grupo Específico (aqui favor retirar o sinal indicativo de crase, que foi usado de maneira errada); local da atividade
![erro epracas_21_mar_19 adicionar evento.JPG](https://images.zenhubusercontent.com/5a72125d4b5806bc2bc515f7/c20c2c61-cc3c-4714-a453-e421deb66cdd)

**Comment by jessica-minc** [comment]
ok na produção
