### ISSUE TITLE
Item de menu para adicionar nova unidade gestora aparece para gestor minc mas não aparece para gestor da praça

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#124]
Boa tarde Christian,

 

Segue um e-mail do sistema CEUs do município de Volta Redonda/RJ.

 

Atenciosamente,

 

Departamento de Obras e Gestão de Equipamentos Culturais

CGGEQ / DOGEC / SECRETARIA DE INFRAESTRUTURA CULTURAL / MINISTÉRIO DA CULTURA

SCS 09, Lote “C”, Torre “B”, 12º andar – Ed. Parque Cidade Corporate

CEP: 70308-200 – Brasília/DF

 

De: Andre Felipe Chaves [mailto:andre.chaves@voltaredonda.rj.gov.br] 
Enviada em: quinta-feira, 24 de maio de 2018 12:25
Para: sistemaceus@cultura.gov.br
Cc: Aline Ribeiro <aline.ribeiro@voltaredonda.rj.gov.br>
Assunto: Solicitação de inserção de informações no e-praças

 

Prezados boa tarde,

 

Gostaria de solicitar a permissão para inserção de informações no site do E-praças no item “UNIDADE GESTORA LOCAL” pois o mesmo não aparece  editável para mim que estou como gestor do SISTEMA.(Print da tela em anexo a este)

 

Para tanto, seguem minhas informações:

NOME: ANDRÉ FELIPE FERREIRA CHAVES

C.P.F.: 092.388.487-42

E-MAIL CADASTRADO: felipechavesvr@gmail.com

**Comment by chris-redfield** [comment]
![image003.jpg](https://images.zenhubusercontent.com/5a2969e48a75884b908a439f/94159d39-8c8d-4ec3-b2b7-842e202f1e01)

**Comment by jessica-minc** [comment]
ok em homolog
