### ISSUE TITLE
Cadastro do grupo gestor sendo solicitado mais de 1 vez

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#133]
O gestor adicionou o Grupo Gestor e anexou os documentos de constituição.

Mas ao apertar o botão laranja de + para adicionar cada membro, o sistema continua pedindo o cadastro do Grupo Gestor ao invés de dar o formulário de cadastro de cada membro

![image003.png](https://images.zenhubusercontent.com/5a2969e48a75884b908a439f/099b8592-5883-4f2f-80e3-818274bea11a)

**Comment by jessica-minc** [comment]
não foi para produção

**Comment by jessica-minc** [comment]
testei nessa praça https://epracas.cultura.gov.br/pracas/808e613b-3b5a-41dd-af7f-454f8fb964a9 e deu certo. Agora precisamos pensar numa maneira mais intuitiva que "Para opções relacionadas ao gupo gestor, utilize o menu acima." mas essa não é prioridade no momento

**Comment by clebersantos** [comment]
Ok. Vou fechar esta issue tendo em vista que o  problema reportado foi corrigido. Para as melhorias, abriremos outra issue para tratarmos em um segundo momento.

**Comment by jessica-minc** [comment]
Cleber, não seria melhor já abri esse card de melhoria e deixar no backlog?

**Comment by clebersantos** [comment]
@jessica-minc para as melhorias teremos uma reunião de planejamento, serão novas issues com maiores detalhes do que deve ser melhorado.
