### ISSUE TITLE
Parceiros da Praça - Fotos

### ISSUE THREAD

**Issue by volthier** [culturagovbr/epracas-frontend#138]
Ao enviar a foto do avatar dos parceiros a mesma apresenta erro.

![print de erro.png](https://images.zenhubusercontent.com/5a68701f4b5806bc2bc417c4/ed44e36f-d09a-490c-8bbf-c6d6c93643f1)

**Comment by jessica-minc** [comment]
não foi para produção

**Comment by jessica-minc** [comment]
consegui incluir e excluir fotos. Agora precisamos implementar uma forma intuitiva de passar por todas as fotos, sem ter que clicar em 'fotos>mais>mais" exemplo:
https://epracas.cultura.gov.br/pracas/da729a70-0506-4e15-a6d2-423b510f421d/galeria

**Comment by clebersantos** [comment]
Ok. Vou fechar esta issue tendo em vista que o  problema reportado foi corrigido. Para as melhorias, abriremos outra issue para tratarmos em um segundo momento.

**Comment by jessica-minc** [comment]
sugiro abrir card de melhoria e deixar no backlog
