### ISSUE TITLE
Remover os arquivos do Grupo Gestor da praça de ESTEIO

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#148]
https://epracas.cultura.gov.br/pracas/9c36875c-b550-4c48-820d-b67103e8f1cb

Remover pontualmente esses arquivos que foram inseridos para teste.

![Screenshot from 2018-10-03 10-35-40.png](https://images.zenhubusercontent.com/5a2969e48a75884b908a439f/abc4de62-3fc7-4dee-8f38-43414da8ac74)

**Comment by jessica-minc** [comment]
não foi removido na produção
