### ISSUE TITLE
inserir informações do limite máximo de tamanho de documento

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#152]
Inserir tamanho máximo de documento no grupo gestor !
estatuto etc

**Comment by chris-redfield** [comment]
![image.png](https://images.zenhubusercontent.com/5a2969e48a75884b908a439f/6039c5af-3f96-46e1-9bda-96204413bcd7)

**Comment by jessica-minc** [comment]
não foi para produção

**Comment by jessica-minc** [comment]
não apareceu mensagem ao tentar subir arquivo com mais de 43 mega

**Comment by Pedro-Philipe** [comment]
@jessica-minc acabei de testar essa issue, e a imagem aparece no corpo da caixa de dialogo. Teria mais informações, ou imagens para me ajudar a simular este erro?

![image.png](https://images.zenhubusercontent.com/5a58ea374b5806bc2bc288bf/1da32636-050a-4a76-a8a8-93108e6ed070)

**Comment by jessica-minc** [comment]
Agora está ok

**Comment by jessica-minc** [comment]
ok na produção
