### ISSUE TITLE
Adicionar novo campo nos membros do grupo gestor

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#156]
Adicionar campos email e telefone aos membros (infomação exclusiva para o ministério da cultura)

Esses campos não serão visualizáveis publicamente, somente gestores minc

**Comment by avaloni** [comment]
Os campos precisam ser opcionais.

**Comment by jessica-minc** [comment]
não foi para produção

**Comment by jessica-minc** [comment]
não foi feito
![erro epracas_13_mar_19_Campos de Contato GG.JPG](https://images.zenhubusercontent.com/5a72125d4b5806bc2bc515f7/d32fa5e8-e06c-44ae-bd66-93a34147f093)

**Comment by jessica-minc** [comment]
ok na produção
