### ISSUE TITLE
Restaurar dados do sistema - dados estão bagunçados

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#25]
Todas as praças estão com status "estranho", por exemplo:

https://dev.epracas.cultura.gov.br/pracas/417f466c-b5c3-4d5d-b218-91098f68426a -> estava com status inaugurada

https://dev.epracas.cultura.gov.br/pracas/2611bd41-72f1-4753-a008-8bd0ec0b325e -> estava com status de inaugurada

Precisamos checar a restauração que foi feita, segundo equipe de negócio: a impressão é que os dados não foram atualizados, foram sobrescritos. Os bancos passados para a CGTEC não tinham informação de status
epracas de produção não está conseguindo recuperar os dados - checar o problema com o banco

Condições de aceitação:

- [x] epracas conseguir recuperar os dados do backend e mostrar as pracas na interface
- [x] epracas estar com as informações em conformidade com os dados enviados pelo time de negócio

**Comment by chris-redfield** [comment]
O ambiente Dev não está espelhando Produção periodicamente de forma automática.

**Comment by chris-redfield** [comment]
As situações estão OK, no entanto alguns dados estão faltando ou não foram atualizados com a planilha:

- Data da inauguração
- Valor do repasse
- Contrato (conferir)
- Modelo (conferir)

**Comment by chris-redfield** [comment]
Nome também é para atualizar, caso seja uma string e não 0 (zero)

**Comment by isatami** [comment]
Checado agora à tarde no dev. Parece estar OK. Se puderem subir para a produção será ótimo.

**Comment by isatami** [comment]
Na produção ainda está com inconsistências:
Exemplos as três do DF e a de Lavras/MG
