### ISSUE TITLE
Ajustes grupo gestor

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#32]
- [x] Gestor da praça precisa conseguir editar, adicionar e encerrar o grupo gestor também (e excluir o membro), atualmente somente o gestor MINC está conseguindo essas operações.
- [x] No título está escrito "Adicione um parceiro da praça"
- [x] No momento da exclusão de membro do grupo gestor (após informar a data de desligamento), o sistema está apresentando problema da foto abaixo[Uploading... epracas erro1.png ]

**Comment by chris-redfield** [comment]
Essa parte não foi feita pois ainda não houve consenso sobre a exclusão e a edição não é tão prioritária: 

Gestor da praça precisa conseguir editar, adicionar e encerrar o grupo gestor também (e excluir o membro), atualmente somente o gestor MINC está conseguindo essas operações.

A regra de negócio também não ficou muito clara para a equipe, vamos revisitar essa tarefa nas próximas sprints, conforme prioridade

**Comment by isatami** [comment]
- Está funcionando inserir membro;
- Quando clicamos em "Grupo Gestor" é possível visualizar todos os Grupos cadastrados;

Problemas:
- Quando editamos os cards a página corre para o topo;
- Não há opção para excluir um membro de um Grupo vigente; só há opção de excluir membros de Grupos encerrados;
- Ao tentar excluir um membro de um grupo encerrado, aparece o seguinte erro:
![image.png](https://images.zenhubusercontent.com/5a6b7ec04b5806bc2bc47578/d40a6d46-44d2-4142-88b4-acdbff977b92)
- Quando abrimos a lista de Grupos Gestores e clicamos para visualizar documentos de um Grupo o card todo fica clicável, mas só é possível clicar efetivamente no ícone de documento;
- Uma observação: a visualização do conteúdo do card de cada membro está dificultada porque as fontes estão muito claras, pequenas e aparentam baixa definição:
![image.png](https://images.zenhubusercontent.com/5a6b7ec04b5806bc2bc47578/65c34df4-d7a7-439f-acfd-359353699e9c)

**Comment by isatami** [comment]
Ao finalizar o Grupo Gestor é solicitada a data de finalização, mas o texto na parte azul do card diz "Gestão iniciada em":
![image.png](https://images.zenhubusercontent.com/5a6b7ec04b5806bc2bc47578/8b128284-eaf6-4300-865e-d354c898e9ba)

**Comment by isatami** [comment]
Quando tentei finalizar o Grupo após a inserção da data de encerramento e o acionamento de "enviar", apareceu o seguinte erro:

![image.png](https://images.zenhubusercontent.com/5a6b7ec04b5806bc2bc47578/6d66372d-e838-4f90-87b7-d6e612bb05c8)

**Comment by chris-redfield** [comment]
OK, vamos jogar essa issue para a sprint 3, pois foi verificado que a funcionalidade está bugada

**Comment by ryubr** [comment]
Falta fechar a modal na hora de encerrar.

**Comment by isatami** [comment]
Corrigir o texto "Membro gestor" para "Adicione um membro do Grupo Gestor"
![image.png](https://images.zenhubusercontent.com/5a6b7ec04b5806bc2bc47578/6ce56a75-2f94-497f-a4ba-c7b386c5c0f8)

**Comment by isatami** [comment]
Não há opção para excluir um membro de um Grupo vigente; só há opção de excluir membros de Grupos encerrados;

**Comment by isatami** [comment]
Ao finalizar o Grupo Gestor é solicitada a data de finalização, mas o texto na parte azul do card diz "Gestão iniciada em":

**Comment by isatami** [comment]
Consegui finalizar um Grupo, mas apareceu uma mensagem "gestão iniciada" e não "gestão encerrada"

**Comment by isatami** [comment]
Ao encerrar o grupo atual, fica como se não houvesse grupo nenhum, ainda que haja vários cadastrados anteriormente.
Um solução seria mudar a mensagem para: "Os dados sobre o Grupo Gestor atual não foram inseridos nesta Praça. Para consultar Grupos Gestores eleitos anteriormente, acesse o link "Grupo Gestor" acima"".

![image.png](https://images.zenhubusercontent.com/5a6b7ec04b5806bc2bc47578/5ad577dc-0bf3-4c68-92d0-de30649b7773)
