### ISSUE TITLE
Adicionar parceiros

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#33]
- [x] Telefone não está aceitando números de 8 dígitos (só aceita celular)
- [x] Ao incluir o valor da parceria (quando envolve recursos financeiros), o sistema não está aceitando ponto  como separador de milhar, ao usar o ponto ele entende que ele é um separador de casas decimais. A vírgula, por sua vez, não é aceita de forma alguma, e é tratada como caractere não numérico (400000,90 não é aceito) - verificar máscaras - backend e frontend

- [x] Ao editar, caso a parceria não envolva repasse, o epracas mesmo assim pede que o campo seja informado, mesmo que o switch esteja "desligado"

**Comment by jessica-minc** [comment]
Testamos as três ocorrências. O campo telefone continua exigindo 9 dígitos. O valor da parceria não reconhece vírgula para separar os decimais. Ao editar o parceiro não foi possível salvar as informações, com ou sem recursos financeiros.

**Comment by isatami** [comment]
Tudo funcionando

**Comment by isatami** [comment]
Tudo funcionando

**Comment by isatami** [comment]
Arrastar para Closed (não consigo!)

**Comment by chris-redfield** [comment]
Olá @isatami ! Acabamos de testar o campo de telefone e conseguimos alterálo para 8 dígitos, pode testar novamente ?

**Comment by isatami** [comment]
Está funcionando o campo do telefone e a questão dos recursos financeiros

**Comment by isatami** [comment]
Segue sem funcionar o "Adicionar parceiro" pelo menu da bolinha vermelha lá em cima

**Comment by chris-redfield** [comment]
@isatami , perfeito, vou dar como fechado o card mas abrimos a issue #57 na sprint 3 para correção do botao adicionar parceiro no menu vermelho
