### ISSUE TITLE
Replicar botão X e FECHAR em todas as modais do epracas

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#34]
Replicar padrão de modal acima no sistema todo ( #24)

modal de Unidade Gestora Local não está com os botoes necessários, porém é porque ela não vai mais existir

**Comment by RamonCanabarro** [comment]
Depois de consultas com colegas incluindo @chris-redfield e @volthier, adicionamos botões de fechamento em todas as modais cujo fechamento era somente possível com ESC.  Com exceção às modais de confirmação dada a sua sucintez.

**Comment by chris-redfield** [comment]
Ainda há modais que não foram resolvidas, no entanto para o que foi previsto na sprint, estamos considerando como feito

**Comment by isatami** [comment]
Não aparece nos formulários de cadastro de "Atividades" (ou "Adicionar evento") nem no "Informações sobre a Praça"

**Comment by chris-redfield** [comment]
Opa @isatami , no "Adicionar evento" realmente não tem, vamos colocar. No Informações sobre a Praça, há o X e o Cancelar, vou subir uma foto aqui, não é isso que aparece para vocês ? ![Screenshot from 2018-02-16 15-42-53.png](https://images.zenhubusercontent.com/5a2969e48a75884b908a439f/e103426e-a72c-49e7-b365-6a13ea1687d5)
