### ISSUE TITLE
Nova forma de apresentação dos cards na tela da praça

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#35]
Agora no Grupo Gestor, Parceiros etc, os cards serão apresentados de forma diferente.

Ajustes finais de cada modal da praca.
- [x] Modal Parceiros - Campos obrigatorio não fica selecionado na modal de parceiros.
- [x] Modal Grupo Gestor - Campos forma de constituicao não vem marcado, o parceiro não esta podendo editar os membros.
- [x] Modal Recursos Humanos - Colocar campo remuneração só numeros, colocar mascara, não recupera todos os dados.
- [x] Modal Ator - Campo obrigatorio, area atuacao e descricao.
- [x] Modal exclusao recurso humano - Fora do padrao e não esta excluindo.
- [x] Modal exclusao grupo gestor - Fora do padrao e não esta excluindo.
- [x] Modal exclusao parceiro - Não esta excluindo.

**Comment by isatami** [comment]
Os novos cards são ótimos, porém, a fonte parece pequena e apagada ou em baixa definição, dificultando a leitura:

![image.png](https://images.zenhubusercontent.com/5a6b7ec04b5806bc2bc47578/71683ea6-34e5-4c73-acda-c79ec826848e)

**Comment by isatami** [comment]
Exclusão e edição de cada parceiro funcionando; o único problema é que o sistema te joga pro topo da tela ao final

**Comment by isatami** [comment]
Edição de Recurso Humano funcionando, mas o sistema te joga para o topo da tela

**Comment by isatami** [comment]
Exclusão de Recurso humano não se efetiva após apertar o botão "encerrar". O card segue aberto na seguinte tela:
![image.png](https://images.zenhubusercontent.com/5a6b7ec04b5806bc2bc47578/257b5dd1-9bb9-44d5-bd19-c901b4fff861)

**Comment by isatami** [comment]
Edição de "Atores" funcionando. A resolução desse card parece mais nítida (parece que a fonte está mais escura):

![image.png](https://images.zenhubusercontent.com/5a6b7ec04b5806bc2bc47578/f4cd5574-23e6-4c49-a7b2-71c18b6644a8)

**Comment by isatami** [comment]
Após a edição de atores o sistema te joga para o topo da tela

**Comment by isatami** [comment]
A lista de "descrição das atividades do ator" não está em ordem alfabética;
Essa lista deveria incluir "outras" e também poder ficar em branco

**Comment by chris-redfield** [comment]
@isatami , vamos fechar esse card pois entedemos que o objetivo dele foi cumprido. Para as ressalvas colocadas, criamos alguns cartões na sprint #3.
