### ISSUE TITLE
Card das praças serem totalmente clicáveis

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#36]
Atualmente é necessário clicar em um ícone (seta "acessar essa praça"). à partir de agora é desejável clicar somente no card.

**Comment by jessica-minc** [comment]
Testei hoje. Não está clicável, ainda é necessário clicar no ícone (seta para baixo)

**Comment by isatami** [comment]
OK. Arrastar para Closed
