### ISSUE TITLE
Mostrar todos os dados do RH, no padrão dos parceiros

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#37]
Para o público geral não pode aparecer:
- [x] Número do documento
- [x] Remuneração

Porém o gestor da praça e gestor minc pode visualizar essas informações

**Comment by isatami** [comment]
Está funcionando, mas precisa melhorar a visualização do card - definição da fonte e nitidez:
![image.png](https://images.zenhubusercontent.com/5a6b7ec04b5806bc2bc47578/c1324aab-c279-47fe-bab0-a4e86d8e4a28)

**Comment by chris-redfield** [comment]
OK @isatami , vamos fechar esse cartao, mas a regularização das fontes das modais já está prevista para a próxima sprint, card #53

**Comment by isatami** [comment]
ok no ambiente de produção
