### ISSUE TITLE
Parceiros - disponibilizar todos os dados cadastrados

### ISSUE THREAD

**Issue by jorgeluizjr** [culturagovbr/epracas-frontend#4]
Não é possível visualizar todos os dados cadastrados.

**Comment by chris-redfield** [comment]
- [ ] Cada Parceiro será um card agora
- [ ] Se eu for administrador ( tanto daquela praça quanto do minc) aparerão os botões de editar e excluir
- [ ] Cada card poderá ser aberto para checagem dos dados completos clicando em qualquer lugar nele

**Comment by chris-redfield** [comment]
Essa lógica poderia ser aplicada às demais informações do sistema
