### ISSUE TITLE
Logo do e-praças não é clicável

### ISSUE THREAD

**Issue by RamonCanabarro** [culturagovbr/epracas-frontend#42]
Quando se faz a rolagem para baixo, o cabeçalho fixa-se na parte de cima da página e o logo do e-praças aparece à esquerda porém o logo não é clicável

![image.png](https://images.zenhubusercontent.com/5a7066084b5806bc2bc4dbed/d1e8c5ba-5499-4df4-8068-1f1affbf6d29)

**Comment by isatami** [comment]
funcionando. Arrastar essa issue para closed

**Comment by isatami** [comment]
funcionando na produção. Observação:
Quando clico, ele me direciona para o fim da página inicial, daí tenho que rolar pra cima pra chegar no início mesmo. Com certeza vai confundir a galera...
 [Uploading... image.png ]
