### ISSUE TITLE
mostrar todos os eventos da praça

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#46]

**Comment by chris-redfield** [comment]
mostrar 4 eventos na mesma tela da praça e na pesquisa dos eventos da praça. um link com "ver agenda completa"  enviaria para a tela de agenda

**Comment by ryubr** [comment]
Só lembrando que a tela para onde o usuário será redirecionado é a de pesquisa de eventos, onde os filtros vão até o município, mas mostrará eventos de outras praças que está na mesmo município que o evento clicado.

**Comment by chris-redfield** [comment]
OK !
