### ISSUE TITLE
atualizar novamente os dados das praças - municipio

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#47]
utilizar a planilha fornecida para atualizar os municipios das praças.

prqças de ceilandia estao como em brasilia

**Comment by chris-redfield** [comment]
Planilha foi enviada por email para a equipe, é necessário encontrar o script usado na semana passada

**Comment by chris-redfield** [comment]
Checar municipios e UFs na base de dados

**Comment by chris-redfield** [comment]
Feito, aguardando homologação

**Comment by chris-redfield** [comment]
Script para importação da planilha: (github não permite subir .py nos comments)
=============================================================

import rows
from pracas.models import Praca

csv = rows.import_from_csv('ceus2.csv')

for praca_csv in csv:
    try:
        praca = Praca.objects.get(contrato=praca_csv.contrato)
    except Praca.DoesNotExist:
        print(praca_csv)
    praca.municipio = praca_csv.municipio
    praca.save()

**Comment by chris-redfield** [comment]
Olá pessoal ! Acabo de rodar a atualização dos municípios. Por favor validem quando possível :).

Abs!

**Comment by jessica-minc** [comment]
como está na homologação:

![erro município 10_maio_18 no dev.PNG](https://images.zenhubusercontent.com/5a72125d4b5806bc2bc515f7/7fca5bad-e298-48de-92bf-bee95680f74d)


Queria perguntar ainda sobre a busca por palavra inexata, ainda. Penso que seria outra issue, mas já informo que ceilandia sem acento não dá resultado nem na produção nem na homologação

**Comment by chris-redfield** [comment]
Opa Jéssica, acabo de checar o mesmo município na produção e está aparecendo ceilândia normal @_@

![Screenshot from 2018-05-15 16-16-03.png](https://images.zenhubusercontent.com/5a2969e48a75884b908a439f/7cd4b2e3-a1fb-466e-abe6-68388f1cacce)

Talvez seja um cache do seu navegador ?  Pode tentar mandar um shift + f5 ou ctrl + f5 pra ver se aparece ? ?

**Comment by chris-redfield** [comment]
Sobre a busca inexata, parece um bug antigo né ? vamo abrir uma issue nova pra resolver isso :D.

Aguardo seu feedback sobre o reload no browser.
