### ISSUE TITLE
Ao adicionar o evento, adicionar opção "Não se aplica" no campo "público específico" 

### ISSUE THREAD

**Issue by ryubr** [culturagovbr/epracas-frontend#48]

**Comment by chris-redfield** [comment]
A opção não se aplica apareceu no formulário, porém não é possível submeter o evento com essa opção selecionada.![Screenshot from 2018-02-23 18-01-30.png](https://images.zenhubusercontent.com/5a2969e48a75884b908a439f/d3fc81a9-21c1-40db-a5a9-63473615558a)
