### ISSUE TITLE
RH - Criar diferentes tipos de visualização por perfil

### ISSUE THREAD

**Issue by jorgeluizjr** [culturagovbr/epracas-frontend#5]
No caso de RH, o ideal seria haver níveis diferentes de visualização para Gestor MinC, Gestor da Praça e cidadão (não deve poder visualizar os dados pessoais e de remuneração).

**Comment by nitaibezerra** [comment]
Esta issue não foi prometida para este primeiro pacote de entregas. Estou removendo desta Milestone e deverá ser reestruturada.

Mais... Esta demanda deve ser mais objetiva. Sugiro reescrever no formato de [Estória de Usuário com Condições de Satisfação](https://www.mountaingoatsoftware.com/agile/user-stories).

**Comment by isatami** [comment]
O issue corresponde à seguinte demanda da prioridade 1:
![image.png](https://images.zenhubusercontent.com/5a6b7ec04b5806bc2bc47578/659e136f-b6f9-4a13-8aae-6544e982c8c5)

Importantíssimo manter!

**Comment by isatami** [comment]
ok

**Comment by isatami** [comment]
ok no ambiente de produção
