### ISSUE TITLE
Permitir editar evento de uma praça

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#52]
perfis de gestor da praça e gestor minc

**Comment by jessica-minc** [comment]
Verificado. Concluído na homologação

**Comment by jessica-minc** [comment]
[Uploading... 1.edicao do evento 22-03.PNG ]

**Comment by chris-redfield** [comment]
Descobrimos que a area e a subarea não eram gravadas no banco.

Estamos trabalhando pra corrigir isso de imediato, primeiro PR, que popula a tabela da entidade:
https://github.com/culturagovbr/epracas-backend/pull/42

**Comment by chris-redfield** [comment]
Olá pessoal !! muito boa tarde!!!
Resolvemos hoje esse problema, está disponível para vocês checarem

OBS: o problema das áreas de atividade foi resolvido, ainda falta o do tipo de atividade, mas peço que vocês validem o da área primeiro, sob a pena de resolver um problema e correr risco de criar outro

**Comment by chris-redfield** [comment]
Investigando a questão da "Atividade" agora.

Por qual razão ela precisa ser selecionada novamente para o formulário funcionar ? provavelmente o objeto recuperado do banco de dados está diferente do esperado

**Comment by chris-redfield** [comment]
Amigos, colocando esse fix em homologação AGORA !! 

Até amanhã!

C
