### ISSUE TITLE
Ordenar alfabeticamente a lista de descrição das atividades do ator

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#56]
A lista de "descrição das atividades do ator" não está em ordem alfabética;
Essa lista deveria incluir "outras" e também poder ficar em branco

**Comment by RamonCanabarro** [comment]
![image.png](https://images.zenhubusercontent.com/5a7066084b5806bc2bc4dbed/510f7ea9-94eb-4441-9d2d-b06611502c32)

Necessárias futuras alterações no backend para possibilitar a criação de novos atores com descrição atividades nulas.

**Comment by ryubr** [comment]
@RamonCanabarro, não seria só colocar o campo como obrigatório no formulário? já q tá obrigatório no back?

**Comment by chris-redfield** [comment]
Essa issue não foi pro deploy.

Checar por qual razão :D
