### ISSUE TITLE
Grupo Gestor - mostrar documentos anexados

### ISSUE THREAD

**Issue by jorgeluizjr** [culturagovbr/epracas-frontend#6]
Deve disponibilizar os documentos anexados no cadastro do Grupo Gestor na página da praça

**Comment by chris-redfield** [comment]
O sistema aparenta estar puxando os mesmos grupos gestores para praças diferentes, esses são os grupos que possuem muitos do dia 19/12

**Comment by chris-redfield** [comment]
Grupo

**Comment by chris-redfield** [comment]
Está escrito "Adicione um parceiro da praça"

Ajustar esse titulo
