### ISSUE TITLE
Remover entradas duplicadas do menu hamburguer da praça

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#62]

**Comment by RamonCanabarro** [comment]
![image.png](https://images.zenhubusercontent.com/5a7066084b5806bc2bc4dbed/e1dff66e-8b91-4529-8ab0-f6de98bf4873)

O hamburguer ficou assim, removemos as opções duplicadas de adição de parceiros e imagens da galeria.

**Comment by chris-redfield** [comment]
Deve ser removido somente o botão dos parceiros.

Favor devolver o botão das fotos
