### ISSUE TITLE
Calendário não registra evento no ultimo dia, quando o evento é sequencial

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#65]

**Comment by isatami** [comment]
Adicionei um evento de 3 dias em Rio Branco: início 02/03/2018; término: 03/03/2018, com repetição anual.
No calendário ele aparece aparece nesses dias, mas não aparece a informação sobre a repetição anual na página do evento

**Comment by isatami** [comment]
Acho que fica melhor se tiver um título: Próximos eventos em baixo de "Agenda" e se o link "Agenda" virar "Agenda Completa da Praça". Já que ao clicar o usuário é direcionado a outra página...

**Comment by isatami** [comment]
Outro aprimoramento seria acrescentar o botão laranja de + no canto direito para que o usuário acrescente um evento (mantendo a mesma lógica dos demais campos).
E
