### ISSUE TITLE
Tela branca ao acessar o sistema

### ISSUE THREAD

**Issue by jorgeluizjr** [culturagovbr/epracas-frontend#8]
Ao acessar o sistema https://epracas.cultura.gov.br, é apresentado tela branca, após executar o refresh é apresentado a tela inicial do sistema normalmente.

**Comment by chris-redfield** [comment]
Esse bug ocorre pois a lib de auth atual não esta renovando o token automaticamente com o ID CULTURA. 
Estamos trocando a biblioteca de autenticação para uma nova.

**Comment by chris-redfield** [comment]
Esse problema nunca mais ocorreu. Considerarei como corrigido e se necessário reabrimos
