### ISSUE TITLE
Mais ajustes no grupo gestor

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#88]
observações retiradas da issue #32
1. Ao finalizar o Grupo Gestor é solicitada a data de finalização, mas o texto na parte azul do card diz "Gestão iniciada em":
2. Corrigir o texto "Membro gestor" para "Adicione um membro do Grupo Gestor"
3. Corrigir o texto "para opções relacionadas ........ utilize o menu ao lado" para "... acima"
4. Depois de excluir o membro de um Grupo encerrado, a modal se fecha autormaticamente
5. Consegui finalizar um Grupo, mas apareceu uma mensagem "Grupo Gestor Adicionado" e não "Grupo Gestor Encerrado" no toast
6. Ao encerrar o grupo atual, fica como se não houvesse grupo nenhum, ainda que haja vários cadastrados anteriormente.
Um solução seria mudar a mensagem para: "Os dados sobre o Grupo Gestor atual não foram inseridos nesta Praça. Para consultar Grupos Gestores eleitos anteriormente, acesse o link "Grupo Gestor" acima"".
7. No título está escrito "Adicione um parceiro da praça"

**Comment by volthier** [comment]
Os itens de atualização que foram efetuados são: 1, 2, 3, 5, 6 e 7.

Devido a complexidade do item 4 o mesmo será revisado junto a equipe para averiguação de impacto.
