### ISSUE TITLE
Criar botão "+" adicionar para os eventos e para as imagens

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#92]
Retirar os respectivos botões do menu da praça (hamburguer)

**Comment by jessica-minc** [comment]
Verificado no homolog

**Comment by isatami** [comment]
Como foi colocado o botão + para eventos, tirar a opção "adicionar evento" do hambúrguer vermelho no topo

**Comment by chris-redfield** [comment]
OK, vou resolver isso na próxima entrega blz ?
