### ISSUE TITLE
Incluir município e UF nas informações básicas da praça

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#96]
Incluir isso no cartão preto, onde está nome, metragem etc.

Essas informações devem ser não editáveis no formulário "incluir informações sobre a praça"

**Comment by chris-redfield** [comment]
UF em maiúsculo, somente a sigla

**Comment by chris-redfield** [comment]
Essas informações devem ser não editáveis no formulário "incluir informações sobre a praça"

**Comment by jessica-minc** [comment]
As informações de Município e UF não estão editáveis para gestor da Praça. OK.
Entretanto, ao editar outras informações não foi possível enviá-las. No print abaixo, o texto, o telefone e email. Neste caso, o campo uf fica como obrigatório, mas não preenchido e bloqueado para edição
![erro ao enviar editar informações da praça no epracas.png](https://images.zenhubusercontent.com/5a72125d4b5806bc2bc515f7/6eb8d7fb-a0f6-4a53-b61f-310b3ee11d18)

**Comment by jessica-minc** [comment]
![infos da Praça - UF.png](https://images.zenhubusercontent.com/5a72125d4b5806bc2bc515f7/7db329bd-1969-4593-8916-d127c9c0cedf)

**Comment by isatami** [comment]
A sigla da UF está aparecendo em minúsculas:
![image.png](https://images.zenhubusercontent.com/5a6b7ec04b5806bc2bc47578/076ea423-734b-4fef-808a-46935854acdf)

**Comment by chris-redfield** [comment]
OK, ainda estamos com problemas.

Vou fechar essa issue, considerando que minimamente o municio e a UF estão aparecendo, mas vou criar novas issues para checar por que razão eles estão voltando com letras minúsculas.

Além disso, checar também por que razão o gestor da praça não está conseguindo atualizar as as informações

**Comment by isatami** [comment]
Não é possível enviar as informações editadas:

![image.png](https://images.zenhubusercontent.com/5a6b7ec04b5806bc2bc47578/41c43d0e-08d4-4755-a459-8453b48ce154)

**Comment by isatami** [comment]
Além disso, as informações de Logradouro, CEP, Município, UF, Região e Bairro, não deveriam ser editáveis. Parece que por a UF estar não editável mas obrigatória está travando o botão enviar

![image.png](https://images.zenhubusercontent.com/5a6b7ec04b5806bc2bc47578/2cbe2ec5-d. 259-4948-ba56-2f0357596c0d)

**Comment by chris-redfield** [comment]
Feito!!! Testando em homolog rapidamente, já vou jogar em prod por tratar-se de hotfix

**Comment by chris-redfield** [comment]
Correção disponibilizada em produção

**Comment by chris-redfield** [comment]
SEINFRA nos reportou novos bugs. Dessa vez o problema é no backend, que não permitia que o gestor praça editasse essas informações

**Comment by jessica-minc** [comment]
Não é possível editar informações da praça. Provavelmente pq UF ta travada. Esse problema já havia sido corrigido e voltou

![erro epracas_26_mar_19_editar informações da praça.JPG](https://images.zenhubusercontent.com/5a72125d4b5806bc2bc515f7/4449c356-1b5b-43ea-a670-f3ce952be095)

**Comment by jessica-minc** [comment]
Editar informações da praça	O gestor da praça não poderia editar os campos: número de contrato; calor de repasse; situação da obra; e modelo. Esses campos devem ser de edição restrita ao administrador Gestor MinC. Entretanto, no teste no homolog foi possível editar sendo somente gestor da Praça. Correção urgente.

O campo Página nas redes sociais também deu erro, não aceitou nenhum preenchimento.

**Comment by Pedro-Philipe** [comment]
@jessica-minc tentou também colocar o http:// ou https:// antes da url dos links no campo de páginas? Pra ficar mais intuitivo vou colocar um exemplo no campo que some ao focar o lugar de preencher.

**Comment by jessica-minc** [comment]
No dev agora:
O gestor não pode mais editar os campos: número de contrato; valor de repasse; situação da obra; e modelo - ok

Página nas redes sociais - com http:// deu certo, mas solicitamos que não seja obrigatório porque a maioria dos gestores não sabe que o que é. Se não for possível retirar a obrigatoriedade, é possível já deixar esse início preenchido?

Observa-se no print que o nome do município está com letra minúscula, que remete a issue #158, que já tinha sido homologada e voltou a dar erro no dev.epracas.cultura.gov.br


![erro pracas editar info praca 10_abr_19.JPG](https://images.zenhubusercontent.com/5a72125d4b5806bc2bc515f7/37ec5546-5af3-4b38-b2d9-96a942b51411)

**Comment by jessica-minc** [comment]
Na produção agora:
O gestor não pode mais editar os campos: número de contrato; valor de repasse; situação da obra; e modelo - ok

Página nas redes sociais - com http:// deu certo, mas solicitamos que não seja obrigatório porque a maioria dos gestores não sabe que o que é. Se não for possível retirar a obrigatoriedade, é possível já deixar esse início preenchido?

O campo Página nas redes sociais também deu erro, não aceitou nenhum preenchimento. Só funciona com http:// - melhor seria se tivesse o recado “formato obrigatório” http://www.exemplo.com.br ou se já deixasse preenchido para o gestor só completar.

**Comment by Pedro-Philipe** [comment]
@jessica-minc Acho mais interessante a idéia do formato obrigatório do que já deixar preenchido, muitas vezes quando a URL é copiada no navegador, ele já traz automaticamente o http

**Comment by jessica-minc** [comment]
testando no dev agora, continua em minúsculo o nome do município em duas telas que eu pude observar: editar informações da praça e pedidos de vinculação (esta, exclusiva do gestor minc)

![erro epracas_20_maio_19_nome em caixa baixa](https://user-images.githubusercontent.com/35741445/58043387-6de79780-7b13-11e9-9ed6-3fb4a1d9d01e.JPG)


![erro epracas_20_maio_19_nome em caixa baixa 2](https://user-images.githubusercontent.com/35741445/58043396-73dd7880-7b13-11e9-96b7-710b273e0567.JPG)
