### ISSUE TITLE
Mapa "preview" não está mais aparecendo na página da praça

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/epracas-frontend#98]
Antes, no final da página da praça, havia um mapa mostrando onde ela estava situada. Trazer de volta essa funcionalidade.

**Comment by jessica-minc** [comment]
não foi corrigido![erro epracas_13_mar_19_mapa da praça.JPG](https://images.zenhubusercontent.com/5a72125d4b5806bc2bc515f7/754d66fd-a5dd-482b-832a-2d902482076e)

**Comment by jessica-minc** [comment]
Mapa no "pracas CEUs próximas a mim" dos EUA
![erro epracas_13_mar_19_praças proximas a mim.JPG](https://images.zenhubusercontent.com/5a72125d4b5806bc2bc515f7/46ed74b8-0a52-4906-9658-fb3df7982cb6)

**Comment by jessica-minc** [comment]
![erro pracas proximas 8_abr_19.JPG](https://images.zenhubusercontent.com/5a72125d4b5806bc2bc515f7/4d9caef8-12e0-4e37-bab8-12c3b08060b3)

**Comment by Pedro-Philipe** [comment]
@jessica-minc Poderia verificar se o erro também ocorre quando a localização do seu navegador não está bloqueada? Se for isso, vou providenciar algum tipo de alerta sobre o bloqueio

**Comment by jessica-minc** [comment]
não sei como bloqueia ou desbloqueia localização do navegador

**Comment by jessica-minc** [comment]
Ok – depois de clicar em permitir “o e-praças quer saber sua localização”
